### PR TITLE
Update modifiers

### PR DESCRIPTION
**Pull request by yaauie**
Added support and tests for the update modifiers I needed for a project:
- `$set` (added tests)
- `$unset`
- `$push`
- `$pop`
- `$addToSet`

### CODE REVIEW

**Comment by gdb** [comment]
The functionality here looks great, thanks! Just some minor style nits to address.

**Comment by yaauie** [comment]
Heh. I'll take the time to refactor this weekend and resubmit.

**Comment by gdb** [comment]
Any interest in revising the patch? Would love the functionality!

**Comment by yaauie** [comment]
Stumbled upon this five and a half years later and realised I _completely_ dropped it on the floor.

😩😩😩

Closing because it's stale and I realistically don't have the time to get to it.

**Pull request closed without merging**
